---
# Service Account for ArgoCD Application Controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-argocd-application-controller
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: workshop-argocd-application-controller
    app.kubernetes.io/part-of: low-latency-workshop
---
# ClusterRole for ArgoCD Application Controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-argocd-application-controller
  labels:
    app.kubernetes.io/name: workshop-argocd-application-controller
    app.kubernetes.io/part-of: low-latency-workshop
rules:
# Core Kubernetes resources
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
# Apps resources
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
# Extensions resources
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
# Networking resources
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
# RBAC resources
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
# OpenShift specific resources
- apiGroups: ["route.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["image.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["build.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["template.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  verbs: ["use"]
  resourceNames: ["anyuid", "privileged"]
# Performance and tuning resources
- apiGroups: ["performance.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["tuned.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
# SR-IOV resources
- apiGroups: ["sriovnetwork.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
# Virtualization resources
- apiGroups: ["kubevirt.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["hco.kubevirt.io"]
  resources: ["*"]
  verbs: ["*"]
# Monitoring resources
- apiGroups: ["monitoring.coreos.com"]
  resources: ["*"]
  verbs: ["*"]
# Operators
- apiGroups: ["operators.coreos.com"]
  resources: ["*"]
  verbs: ["*"]
# Custom resources
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
---
# ClusterRoleBinding for ArgoCD Application Controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-argocd-application-controller
  labels:
    app.kubernetes.io/name: workshop-argocd-application-controller
    app.kubernetes.io/part-of: low-latency-workshop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workshop-argocd-application-controller
subjects:
- kind: ServiceAccount
  name: workshop-argocd-application-controller
  namespace: openshift-gitops
---
# Service Account for ArgoCD Server
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-argocd-server
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: workshop-argocd-server
    app.kubernetes.io/part-of: low-latency-workshop
---
# ClusterRole for ArgoCD Server
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-argocd-server
  labels:
    app.kubernetes.io/name: workshop-argocd-server
    app.kubernetes.io/part-of: low-latency-workshop
rules:
# Read access to most resources for UI display
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
# ArgoCD specific permissions
- apiGroups: ["argoproj.io"]
  resources: ["*"]
  verbs: ["*"]
---
# ClusterRoleBinding for ArgoCD Server
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-argocd-server
  labels:
    app.kubernetes.io/name: workshop-argocd-server
    app.kubernetes.io/part-of: low-latency-workshop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workshop-argocd-server
subjects:
- kind: ServiceAccount
  name: workshop-argocd-server
  namespace: openshift-gitops
