apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: multiclusterhub-multiclusterhub.yaml
    target:
      kind: MultiClusterHub
      name: multiclusterhub
