---
# User Secrets Workload
# Creates labeled secrets for Dev Spaces auto-mount (kubeconfig and SSH keys)
# Called in a loop with user_num variable
# Idempotent - safe to re-run

- name: Set user facts
  ansible.builtin.set_fact:
    _user_name: "{{ workshop_user_base }}{{ user_num }}"
    _user_namespace: "{{ workshop_namespace_prefix }}{{ workshop_user_base }}{{ user_num }}"
    _sno_guid: "workshop-{{ workshop_user_base }}{{ user_num }}"

# AgnosticD official output file naming convention:
# Pattern: ${output_dir}/${guid}/${env_type}_${guid}_<artifact>
# Where env_type = low-latency-workshop-sno

- name: Set SNO credential paths (AgnosticD naming convention)
  ansible.builtin.set_fact:
    # Primary: AgnosticD official naming pattern (highest priority)
    _sno_kubeconfig_official: "{{ sno_output_dir }}/{{ _sno_guid }}/low-latency-workshop-sno_{{ _sno_guid }}_kubeconfig"
    _sno_kubeadmin_official: "{{ sno_output_dir }}/{{ _sno_guid }}/low-latency-workshop-sno_{{ _sno_guid }}_kubeadmin-password"
    # Fallback: symlink path created by post_software.yml
    _sno_kubeconfig_symlink: "{{ sno_output_dir }}/{{ _sno_guid }}/kubeconfig"
    # SSH key path (AgnosticD naming)
    _sno_ssh_key_path: "{{ sno_output_dir }}/{{ _sno_guid }}/ssh_provision_{{ _sno_guid }}"

- name: Check if SNO kubeconfig exists (official AgnosticD path)
  ansible.builtin.stat:
    path: "{{ _sno_kubeconfig_official }}"
  register: _kubeconfig_official_stat
  delegate_to: localhost

- name: Check if SNO kubeconfig exists (symlink path)
  ansible.builtin.stat:
    path: "{{ _sno_kubeconfig_symlink }}"
  register: _kubeconfig_symlink_stat
  delegate_to: localhost
  when: not _kubeconfig_official_stat.stat.exists

- name: Set actual kubeconfig path (prioritize official AgnosticD path)
  ansible.builtin.set_fact:
    _actual_kubeconfig_path: >-
      {{
        _sno_kubeconfig_official if _kubeconfig_official_stat.stat.exists
        else (_sno_kubeconfig_symlink if (_kubeconfig_symlink_stat.stat.exists | default(false)) else '')
      }}

- name: Check if SSH key exists
  ansible.builtin.stat:
    path: "{{ _sno_ssh_key_path }}"
  register: _ssh_key_stat
  delegate_to: localhost

- name: Create kubeconfig secret for Dev Spaces auto-mount
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ _user_name }}-kubeconfig"
        namespace: "{{ _user_namespace }}"
        labels:
          workshop: low-latency
          student: "{{ _user_name }}"
          managed-by: agnosticd
          # Dev Spaces auto-mount labels
          controller.devfile.io/mount-to-devworkspace: "true"
          controller.devfile.io/watch-secret: "true"
        annotations:
          # Mount as file in .kube directory
          controller.devfile.io/mount-path: "{{ devspaces_kubeconfig_mount_path | default('/home/user/.kube') }}"
          controller.devfile.io/mount-as: subpath
      data:
        config: "{{ lookup('file', _actual_kubeconfig_path) | b64encode }}"
      type: Opaque
  when:
    - devspaces_mount_kubeconfig | default(true) | bool
    - _actual_kubeconfig_path | length > 0

- name: Create kubeconfig placeholder secret if SNO not deployed yet
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ _user_name }}-kubeconfig"
        namespace: "{{ _user_namespace }}"
        labels:
          workshop: low-latency
          student: "{{ _user_name }}"
          managed-by: agnosticd
          status: placeholder
          controller.devfile.io/mount-to-devworkspace: "true"
          controller.devfile.io/watch-secret: "true"
        annotations:
          controller.devfile.io/mount-path: "{{ devspaces_kubeconfig_mount_path | default('/home/user/.kube') }}"
          controller.devfile.io/mount-as: subpath
          description: "Placeholder - will be updated when SNO is deployed"
      stringData:
        config: |
          # Placeholder kubeconfig - SNO cluster not yet deployed
          # This will be updated automatically when the SNO cluster is ready
          apiVersion: v1
          kind: Config
          clusters: []
          contexts: []
          current-context: ""
          users: []
      type: Opaque
  when:
    - devspaces_mount_kubeconfig | default(true) | bool
    - _actual_kubeconfig_path | length == 0

- name: Create SSH key secret for Dev Spaces auto-mount
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ _user_name }}-ssh-key"
        namespace: "{{ _user_namespace }}"
        labels:
          workshop: low-latency
          student: "{{ _user_name }}"
          managed-by: agnosticd
          controller.devfile.io/mount-to-devworkspace: "true"
          controller.devfile.io/watch-secret: "true"
        annotations:
          controller.devfile.io/mount-path: "{{ devspaces_ssh_mount_path | default('/home/user/.ssh') }}"
          controller.devfile.io/mount-as: subpath
      data:
        id_rsa: "{{ lookup('file', _sno_ssh_key_path) | b64encode }}"
      type: Opaque
  when:
    - devspaces_mount_ssh_key | default(true) | bool
    - _ssh_key_stat.stat.exists

- name: Create SSH key placeholder secret if not available yet
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ _user_name }}-ssh-key"
        namespace: "{{ _user_namespace }}"
        labels:
          workshop: low-latency
          student: "{{ _user_name }}"
          managed-by: agnosticd
          status: placeholder
          controller.devfile.io/mount-to-devworkspace: "true"
          controller.devfile.io/watch-secret: "true"
        annotations:
          controller.devfile.io/mount-path: "{{ devspaces_ssh_mount_path | default('/home/user/.ssh') }}"
          controller.devfile.io/mount-as: subpath
          description: "Placeholder - will be updated when SNO is deployed"
      stringData:
        id_rsa: |
          # Placeholder SSH key - SNO cluster not yet deployed
          # This will be updated automatically when the SNO cluster is ready
      type: Opaque
  when:
    - devspaces_mount_ssh_key | default(true) | bool
    - not _ssh_key_stat.stat.exists

- name: Create SNO connection info ConfigMap (auto-mounted to Dev Spaces)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ _user_name }}-sno-info"
        namespace: "{{ _user_namespace }}"
        labels:
          workshop: low-latency
          student: "{{ _user_name }}"
          managed-by: agnosticd
          # Dev Spaces auto-mount labels (works for ConfigMaps too)
          controller.devfile.io/mount-to-devworkspace: "true"
          controller.devfile.io/watch-configmap: "true"
        annotations:
          controller.devfile.io/mount-path: /home/user/sno-info
          controller.devfile.io/mount-as: subpath
      data:
        SNO_GUID: "{{ _sno_guid }}"
        SNO_API_URL: "https://api.{{ _sno_guid }}.{{ subdomain_base_suffix | regex_replace('^\\.', '') }}:6443"
        SNO_CONSOLE_URL: "https://console-openshift-console.apps.{{ _sno_guid }}.{{ subdomain_base_suffix | regex_replace('^\\.', '') }}"
        BASTION_HOST: "bastion.{{ _sno_guid }}.{{ subdomain_base_suffix | regex_replace('^\\.', '') }}"
        USER_NAME: "{{ _user_name }}"
        KUBECONFIG_READY: "{{ 'true' if _actual_kubeconfig_path | length > 0 else 'false' }}"
        SSH_KEY_READY: "{{ 'true' if _ssh_key_stat.stat.exists else 'false' }}"

# Copy secrets to devspaces namespace for auto-mounting
# Dev Spaces creates user workspaces in <username>-devspaces namespace
- name: Set devspaces namespace
  ansible.builtin.set_fact:
    _devspaces_namespace: "{{ _user_name }}-devspaces"

- name: Check if devspaces namespace exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ _devspaces_namespace }}"
  register: _devspaces_ns_check

- name: Copy kubeconfig secret to devspaces namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ _user_name }}-kubeconfig"
        namespace: "{{ _devspaces_namespace }}"
        labels:
          workshop: low-latency
          student: "{{ _user_name }}"
          managed-by: agnosticd
          controller.devfile.io/mount-to-devworkspace: "true"
          controller.devfile.io/watch-secret: "true"
        annotations:
          controller.devfile.io/mount-path: "{{ devspaces_kubeconfig_mount_path | default('/home/user/.kube') }}"
          controller.devfile.io/mount-as: subpath
      data:
        config: "{{ lookup('file', _actual_kubeconfig_path) | b64encode if _actual_kubeconfig_path | length > 0 else '# Placeholder' | b64encode }}"
      type: Opaque
  when: _devspaces_ns_check.resources | length > 0

- name: Copy SSH key secret to devspaces namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ _user_name }}-ssh-key"
        namespace: "{{ _devspaces_namespace }}"
        labels:
          workshop: low-latency
          student: "{{ _user_name }}"
          managed-by: agnosticd
          controller.devfile.io/mount-to-devworkspace: "true"
          controller.devfile.io/watch-secret: "true"
        annotations:
          controller.devfile.io/mount-path: "{{ devspaces_ssh_mount_path | default('/home/user/.ssh') }}"
          controller.devfile.io/mount-as: subpath
      data:
        id_rsa: "{{ lookup('file', _sno_ssh_key_path) | b64encode if _ssh_key_stat.stat.exists else '# Placeholder' | b64encode }}"
      type: Opaque
  when: _devspaces_ns_check.resources | length > 0

- name: Copy SNO info ConfigMap to devspaces namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ _user_name }}-sno-info"
        namespace: "{{ _devspaces_namespace }}"
        labels:
          workshop: low-latency
          student: "{{ _user_name }}"
          managed-by: agnosticd
          controller.devfile.io/mount-to-devworkspace: "true"
          controller.devfile.io/watch-configmap: "true"
        annotations:
          controller.devfile.io/mount-path: /home/user/sno-info
          controller.devfile.io/mount-as: subpath
      data:
        SNO_GUID: "{{ _sno_guid }}"
        SNO_API_URL: "https://api.{{ _sno_guid }}.{{ subdomain_base_suffix | regex_replace('^\\.', '') }}:6443"
        SNO_CONSOLE_URL: "https://console-openshift-console.apps.{{ _sno_guid }}.{{ subdomain_base_suffix | regex_replace('^\\.', '') }}"
        BASTION_HOST: "bastion.{{ _sno_guid }}.{{ subdomain_base_suffix | regex_replace('^\\.', '') }}"
        USER_NAME: "{{ _user_name }}"
        KUBECONFIG_READY: "{{ 'true' if _actual_kubeconfig_path | length > 0 else 'false' }}"
        SSH_KEY_READY: "{{ 'true' if _ssh_key_stat.stat.exists else 'false' }}"
  when: _devspaces_ns_check.resources | length > 0

- name: Display secrets creation status
  ansible.builtin.debug:
    msg:
      - "✓ Secrets created for: {{ _user_name }}"
      - "Namespace: {{ _user_namespace }}"
      - "DevSpaces namespace: {{ _devspaces_namespace }} ({{ 'exists' if _devspaces_ns_check.resources | length > 0 else 'not created yet' }})"
      - "Kubeconfig: {{ 'Available' if _actual_kubeconfig_path | length > 0 else 'Placeholder (SNO not deployed)' }}"
      - "SSH Key: {{ 'Available' if _ssh_key_stat.stat.exists else 'Placeholder (SNO not deployed)' }}"

