---
- name: Remove ManagedCluster from RHACM (if in RHPDS mode)
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - step999
    - destroy_env
  tasks:
    - name: RHACM Cleanup Block
      when:
        - auto_import_to_rhacm | default(false) | bool
        - rhacm_hub_api is defined
        - rhacm_hub_kubeconfig is defined
      block:
        - name: Verify Hub Cluster Access
          kubernetes.core.k8s_info:
            kind: Namespace
            name: open-cluster-management
            api_version: v1
            host: "{{ rhacm_hub_api }}"
            kubeconfig: "{{ rhacm_hub_kubeconfig }}"
            validate_certs: false
          register: __r_hub
          retries: 10
          delay: 5
          until:
            - __r_hub.resources is defined
            - __r_hub.resources | length > 0

        - name: Delete ManagedClusterSetBinding
          kubernetes.core.k8s:
            kubeconfig: "{{ rhacm_hub_kubeconfig }}"
            state: absent
            definition:
              apiVersion: cluster.open-cluster-management.io/v1beta2
              kind: ManagedClusterSetBinding
              metadata:
                name: "workshop-clusters"
                namespace: "workshop-{{ student_name }}"
              spec:
                clusterSet: "workshop-clusters"

        - name: Delete KlusterletAddonConfig
          kubernetes.core.k8s:
            kubeconfig: "{{ rhacm_hub_kubeconfig }}"
            state: absent
            definition:
              apiVersion: agent.open-cluster-management.io/v1
              kind: KlusterletAddonConfig
              metadata:
                name: "workshop-{{ student_name }}"
                namespace: "workshop-{{ student_name }}"

        - name: Delete auto-import-secret
          kubernetes.core.k8s:
            kubeconfig: "{{ rhacm_hub_kubeconfig }}"
            state: absent
            definition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: auto-import-secret
                namespace: "workshop-{{ student_name }}"

        - name: Delete ManagedCluster resource
          kubernetes.core.k8s:
            kubeconfig: "{{ rhacm_hub_kubeconfig }}"
            state: absent
            definition:
              apiVersion: cluster.open-cluster-management.io/v1
              kind: ManagedCluster
              metadata:
                name: "workshop-{{ student_name }}"

        - name: Delete namespace on hub for SNO
          kubernetes.core.k8s:
            kubeconfig: "{{ rhacm_hub_kubeconfig }}"
            state: absent
            kind: Namespace
            name: "workshop-{{ student_name }}"
            api_version: v1
      rescue:
        - name: RHACM cleanup failed
          ansible.builtin.debug:
            msg: "RHACM cleanup failed for workshop-{{ student_name }}"

- name: Import ocp4-cluster cloud provider specific destroy playbook
  ansible.builtin.import_playbook: "../ocp4-cluster/destroy_env_{{ cloud_provider }}.yml"
