---
- name: Step 000 - Pre Infrastructure (SNO)
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
  - step000
  - pre_infrastructure
  tasks:
  - name: Print debug message
    ansible.builtin.debug:
      msg: "Step 000 Pre Infrastructure for SNO"

  - name: Ensure required variables are set for SNO
    ansible.builtin.assert:
      that:
        - ocp4_pull_secret | default("") | length > 0
        - student_name is defined
        - guid is defined
      fail_msg: "Missing required variables: ocp4_pull_secret, student_name, guid"
      success_msg: "All required variables are defined"

  - name: Set SNO-specific facts (only SNO topology, not bastion)
    ansible.builtin.set_fact:
      master_instance_count: 1
      worker_instance_count: 0
      sno_install: true
      # NOTE: bastion_instance_count comes from default_vars.yml/env_vars.yml
      # Don't set it here - allows flexibility per deployment!

  - name: Display SNO deployment information
    ansible.builtin.debug:
      msg:
        - "Deploying SNO cluster:"
        - "  GUID: {{ guid }}"
        - "  Student: {{ student_name }}"
        - "  Cloud Provider: {{ cloud_provider }}"
        - "  OpenShift Version: {{ ocp_version }}"
        - "  Instance Type: {{ master_instance_type | default('m5.4xlarge') }}"
        - "  RHACM Auto-Import: {{ auto_import_to_rhacm | default(false) }}"

  - name: AWS Pre Infrastructure tasks
    when: cloud_provider == "ec2"
    block:
    # Find and set the AWS Availability Zones using on-demand capacity reservations
    - name: Run infra-aws-capacity-reservation
      ansible.builtin.include_role:
        name: infra-aws-capacity-reservation
      vars:
        ACTION: "provision"

    - name: Set availability zones for SNO
      when: agnosticd_aws_capacity_reservation_results.reservations | default({}) | length > 0
      block:
      - name: Set availability zone for SNO master
        vars:
          _r: "{{ agnosticd_aws_capacity_reservation_results.reservations }}"
        ansible.builtin.set_fact:
          aws_availability_zone: "{{ _r.az1.availability_zone | default(_r.masters.availability_zone | default(_r.masters1.availability_zone)) }}"
          openshift_controlplane_aws_zones_odcr: >-
            {{ [
              _r.masters.availability_zone | default(None),
              _r.masters1.availability_zone | default(None),
            ] | select() | list }}
